version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/sample-function1"
      - "/sample-function2"
    schedule:
      interval: "daily"
    groups:
      esbuild:
        patterns:
          - "esbuild*"
      axios:
        patterns:
          - "axios*"
      lodash:
        patterns:
          - "lodash*"
          - "@types/lodash*"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
